---

apiVersion: extensions/v1

kind: Ingress

metadata:
 
  name: traefik-web-ui
 
  namespace: kube-system

spec:
 
  rules:
 
  - host: traefik-ui-dev.niceloo.com
    http:
 
      paths:
 
      - path: /
 
        backend:
 
          serviceName: traefik-web-ui
 
          servicePort: 8080
