apiVersion: apps/v1
kind: Deployment
metadata:
   name: yutong-devops
   namespace: yutong-devops
   labels:
      app: yutong-devops
spec:
  revisionHistoryLimit: 5
  replicas: rep_nu
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: yutong-devops
  template:
    metadata:
      labels:
        app: yutong-devops
    spec: 
      nodeSelector: 
        role: devops
      hostNetwork: true
      containers:
        - name: yutong-devops
          image: IMAGE_NAME
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 9110
          volumeMounts:
          - mountPath: /data/jenkins_home/users
            name: jenkins-users
          - mountPath: /etc/localtime
            name: date
          - mountPath: /data/logs
            name: app-logs
          - mountPath: /data/jenkins_home/jobs
            name: jenkins-jobs
          - mountPath: /data/jenkins_home/nodes
            name: jenkins-nodes
          - mountPath: /data/app/nginx/html/autotest
            name: newman-file-path  

      volumes:
      - name: jenkins-users
        hostPath:
           path: /data/jenkins_home/users
      - name: date
        hostPath:
           path: /etc/localtime
      - name: app-logs
        hostPath:
           path: /data/logs
      - name: jenkins-jobs
        hostPath:
           path: /data/jenkins_home/jobs
      - name: jenkins-nodes
        hostPath:
           path: /data/jenkins_home/nodes
      - name: newman-file-path
        hostPath:
           path: /data/app/nginx/html/autotest


---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: yutong-devops
  name: yutong-devops
  namespace: yutong-devops
spec:
  ports:
    - port: 80
      targetPort: 9110
  selector:
    k8s-app: yutong-devops
