# 存储类定义，需要修改endpoint（注意：存储类不区分命名空间）
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs-storage
provisioner: kubernetes.io/glusterfs
# 回收策略，默认Delete，表示删除PVC的时候会将其对应的存储删除，而Retain则会保留
reclaimPolicy: Retain
# 允许扩容
allowVolumeExpansion: true
parameters:
  resturl: "http://172.31.4.187:8080"
  restauthenabled: "true"
  secretNamespace: "kube-system"
  secretName: "heketi-secret"
  restuser: "admin"
  volumetype: "none"


# 下述资源全部定义在kube-system中
---
apiVersion: v1
kind: Secret
metadata:
  name: heketi-secret
  namespace: kube-system
data:
  # heketi密码使用base64编码后的数据，这里示例数据对应的密码是123456
  key: MTIzNDU2
type: kubernetes.io/glusterfs


