apiVersion: v1
clusters:
- cluster:
    certificate-authority: /data/k8s/secure/ca.crt
    server: https://172.31.4.187:6443
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    user: admin
  name: default-system
current-context: default-system
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate: /data/k8s/secure/admin.crt
    client-key: /data/k8s/secure/admin.key